//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdSpotWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cameraMarksCoordinate
    {
        public int cordID { get; set; }
        public int cameraID { get; set; }
        public int cordXStart { get; set; }
        public int cordYStart { get; set; }
        public int cordXEnd { get; set; }
        public int cordYEnd { get; set; }
        public int markType { get; set; }
    
        public virtual userCameraTable userCameraTable { get; set; }
    }
}
