//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdSpotWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recordPeopleCountTable
    {
        public int recordID { get; set; }
        public int locationID { get; set; }
        public int PeopleCount { get; set; }
        public System.DateTime timeRecorded { get; set; }
    
        public virtual userLocationSurveillanceTable userLocationSurveillanceTable { get; set; }
    }
}
