//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdSpotWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempUserTable
    {
        public int registrationID { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public string validationCode { get; set; }
        public System.DateTime submittedTime { get; set; }
    }
}
