//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdSpotWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userCameraTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userCameraTable()
        {
            this.cameraMarksCoordinates = new HashSet<cameraMarksCoordinate>();
            this.cameraStreamTables = new HashSet<cameraStreamTable>();
            this.webStreamSignalTables = new HashSet<webStreamSignalTable>();
        }
    
        public int cameraID { get; set; }
        public string cameraName { get; set; }
        public string cameraDescription { get; set; }
        public int locationID { get; set; }
        public string cameraCode { get; set; }
        public int operationStatus { get; set; }
        public int operatingStatus { get; set; }
        public int streamStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cameraMarksCoordinate> cameraMarksCoordinates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cameraStreamTable> cameraStreamTables { get; set; }
        public virtual userLocationSurveillanceTable userLocationSurveillanceTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webStreamSignalTable> webStreamSignalTables { get; set; }
    }
}
