//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdSpotWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webStreamSignalTable
    {
        public int signalID { get; set; }
        public int cameraID { get; set; }
        public System.DateTime timeSignaled { get; set; }
    
        public virtual userCameraTable userCameraTable { get; set; }
    }
}
